### ISSUE TITLE
Input populated by spurious files from git repos

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/1deg_jra55_ryf#12]
This input line https://github.com/COSIMA/1deg_jra55_ryf/blob/master/config.yaml#L26 leads to lots of spurious files being linked into the the `work` directory, e.g.
```
work/atmosphere/INPUT/make_ryf/.git/COMMIT_EDITMSG:
  fullpath: /g/data/ik11/inputs/JRA-55/RYF/v1-4/make_ryf/.git/COMMIT_EDITMSG
  hashes:
    binhash: 22ec7701562a961d8119c4af92a98044
    md5: 9bc314d387974df26448af23836f5f23
work/atmosphere/INPUT/make_ryf/.git/HEAD:
  fullpath: /g/data/ik11/inputs/JRA-55/RYF/v1-4/make_ryf/.git/HEAD
  hashes:
    binhash: 48c6644dd466a8ff8d22fbdda382e22a
    md5: 2b74885bd597136c4af661a85538b2a3
```
See https://github.com/COSIMA/1deg_jra55_ryf/blob/master/manifests/input.yaml#L84-L343

Because there are two code repository directories under `/g/data/ik11/inputs/JRA-55/RYF/v1-4`.

Possible solutions:
1. Keep the code for generating the data in a different location
2. Put the data inside a subdirectory and use that as the `input` location, e.g. `/g/data/ik11/inputs/JRA-55/RYF/v1-4/data`
3. Directly link to the files required rather than the directory itself, e.g.
```yaml
    - name: atmosphere
      model: yatm
      exe: /g/data/ik11/inputs/access-om2/bin/yatm_a227a61.exe
      input:
            - /g/data/ik11/inputs/access-om2/input_20201102/yatm_1deg
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.huss.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.licalvf.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.prra.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.prsn.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.psl.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.rhuss.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.rlds.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.rsds.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.tas.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.uas.1990_1991.nc
            - /g/data/ik11/inputs/JRA-55/RYF/v1-4/RYF.vas.1990_1991.nc
```
The also affects the other RYF configs.
