### ISSUE TITLE
Old style collate config should be replaced

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/1deg_jra55_ryf#4]
Config uses old style collate config:

```yaml
collate_walltime: 1:00:00
collate_queue: express
collate_mem: 4GB
collate_ncpus: 1
collate_flags: -n4 -z -m -r
```

Should be changed to:
```yaml
collate:
     walltime: 1:00:00
     mem: 4GB
```

I have deleted the flags argument. Shouldn't be used unless people know what they're doing. Also deleted the queue, doesn't need to run in express if 1 cpu, default is copyq. Default is 1 cpu so deleted that also.
